import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true
window.opacity = 0.9

[font]
size = 6

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 5
